// Generated by CoffeeScript 1.9.2
(function() {
  var ChatManager;

  ChatManager = (function() {
    function ChatManager(io) {
      var broadcast;
      this.io = io;
      this.sockets = [];
      this.bros = [];
      this.messages = [];
      this.io.on('connection', (function(_this) {
        return function(socket) {
          _this.messages.forEach(function(data) {
            socket.emit('message', data);
          });
          _this.sockets.push(socket);
          socket.on('disconnect', function() {
            _this.sockets.splice(_this.sockets.indexOf(socket), 1);
          });
          socket.on('message', function(data) {
            data = {
              name: data.name,
              text: data.msg
            };
            broadcast(_this.sockets, 'message', data);
            _this.messages.push(data);
          });
          return socket.on('identify', function(broChange) {
            _this.bros.splice(_this.bros.indexOf(socket.bro));
            socket.bro = broChange;
            _this.bros.push(socket.bro);
            return broadcast(_this.sockets, 'roster', _this.bros);
          });
        };
      })(this));
      broadcast = (function(_this) {
        return function(sockets, event, data) {
          _this.sockets.forEach(function(socket) {
            socket.emit(event, data);
          });
        };
      })(this);
    }

    return ChatManager;

  })();

  module.exports = ChatManager;

}).call(this);
