// Generated by CoffeeScript 1.10.0
(function() {
  var ins, logRequest, setHeaders;

  ins = require("util").inspect;

  setHeaders = function(req, res, next) {
    res.set("X-Powered-By", "toeknee");
    return next();
  };

  logRequest = function(req, res, next) {
    console.log("[" + req.ip + "] " + req.method + " " + req.url);
    return next();
  };

  module.exports = {
    setHeaders: setHeaders,
    logRequest: logRequest
  };

}).call(this);
