// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var navLink;
    navLink = $('nav a');
    window.console.log("Found " + navLink.length + " nav link elements");
    return navLink.click(function() {
      return window.console.log("Click detected!");
    });
  });

}).call(this);
