// Generated by CoffeeScript 1.10.0
(function() {
  window.spotifyPlaylistFlip = function() {
    window.console.log("Card flip detected!");
    return $('#spotify-playlist-carousel').toggleClass("flipped");
  };

}).call(this);
