// Generated by CoffeeScript 1.9.2
(function() {
  var middlewareUtils;

  middlewareUtils = require(process.env.FOF_SRC + "/server/middleware/utilities.js");

  module.exports = function(server) {
    server.use(middlewareUtils.setHeaders);
  };

}).call(this);
