// Generated by CoffeeScript 1.10.0
(function() {
  var middlewareUtils, path;

  path = require("path");

  middlewareUtils = require(path.join(__dirname, "../middleware/utilities.js"));

  process.on("uncaughtException", function(err) {
    console.error("UNCAUGHT EXCEPTION: " + err);
    return console.error("STACK: \n " + err.stack);
  });

  module.exports = function(server) {
    server.use(middlewareUtils.setHeaders);
    server.use(middlewareUtils.logRequest);
    return server;
  };

}).call(this);
