// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(server) {
    server.use('/', server.loopback["static"]('/home/ubuntu/toekneefof/client/views'));
    server.use('/img', server.loopback["static"]('/home/ubuntu/toekneefof/client/img'));
    server.use('/js', server.loopback["static"]('/home/ubuntu/toekneefof/client/js'));
    server.use('/css', server.loopback["static"]('/home/ubuntu/toekneefof/client/css'));
  };

}).call(this);
